# Generated by Django 4.0.2 on 2022-03-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
