# Generated by Django 4.0.2 on 2022-03-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_usuarios_id_usuarios_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
